<h1>Numpy</h1>


<h2 style="color:blue;">Introduction</h2> 

* NumPy is a Python library used for working with arrays​ 
    
 * NumPy was created in 2005 by Travis Oliphant.​ 
    
* It is open source​ 
    
* The array object in NumPy is called ndarray

* NumPy stands for Numerical Python

<h3 style="color:red;">Why use numpy?</h3>

* has array object which is 50x faster than Python list
  
* functions for working in domain of linear algebra, fourier transform, and matrices​
  
* the array object in NumPy is called ndarray

<h3 style="color:red;"> Why numpy is faster? </h3>

 * NumPy arrays are stored at one continuous place in memory unlike lists (locality of reference)
   
 * written in C or C++ for fast computation (python is partially used)

In [1]:
#install numpy
! pip install numpy

DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [11]:
#check numpy version 

import numpy as np

print(np.__version__)

1.24.4


In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [10]:
 # NumPy is usually imported under the np alias  
# In Python alias are an alternate name for referring to the same thing

import numpy as np 

arr = np.array([1, 2, 3, 4, 5])

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

<h3 style="color:red;"> Dimensions in Arrays </h3>

<h3 style="color:red;"> 0-D Arrays </h3>


In [26]:
import numpy as np

arr = np.array(42)

print(arr)


print("The dimension of the above array is :", arr.ndim)

42
The dimension of the above array is : 0


<h3 style="color:red;"> 1-D Arrays </h3>

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


print("The dimension of the above array is :", arr.ndim)

[1 2 3 4 5]
The dimension of the above array is : 1


In [59]:
#access 1-D array

print(arr[1])

2


In [16]:
#slicing 1-D array

arr[-3:-1] # arr[1:3]   #arr[-3:-1]

array([3, 4])

<h3 style="color:red;"> 2-D Arrays </h3>

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 5, 7, 9], [4, 5, 6,1, 7, 8]])

print(arr)

print("The dimension of the above array is :", arr.ndim)

[[1 2 3 5 7 9]
 [4 5 6 1 7 8]]
The dimension of the above array is : 2


In [30]:
#access 2-D array
print(arr[1, 1:2])


[5]


In [31]:
#slicing of 2-D array
arr[1, 1:3]

array([5, 6])

<h3 style="color:red;"> 3-D arrays </h3>

In [34]:
import numpy as np

arr = np.array([[[1, 2, 3, 6, 8], [4, 5, 6, 77, 8]], [[1, 2, 3, 5, 7], [4, 5, 6, 2, 4]]])

print(arr)

print("The dimension of the above array is :", arr.ndim)


[[[ 1  2  3  6  8]
  [ 4  5  6 77  8]]

 [[ 1  2  3  5  7]
  [ 4  5  6  2  4]]]
The dimension of the above array is : 3


In [35]:
#access 3-D array
print(arr[1,1,1])

#negative indexing
# print(arr[1,1,-1])

5


In [43]:
#slicing 3-D array

# print(arr[0, 1, 1:3])
print(arr[0, 1, 1:4])

[ 5  6 77]


In [46]:
#SPECIFY DIMENSION IN ARRAY
import numpy as np

arr = np.array([3, 6, 99], ndmin=2)
print(arr)

[[ 3  6 99]]


<h3 style="color:red;"> Data Types in Numpy </h3>

Numpy as following datatypes:

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )    

In [48]:
import numpy as np

arr = np.array([3, 6, 9, 21, 34, 66, 90])

# arr = np.array(['car', 'bus', 'bike'])

print(arr.dtype) # checking datatype of array

int32


In [62]:
#Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([3, 6, 8, 0, 34, 66, 90], dtype='i')  # dtype allows us to define the expected data type

# arr = np.array(['car', 'bus', 'bike'], dtype='S') # dtype allows us to define the expected data type

print(arr.dtype) # checking datatype of array

int32


<h3 style="color:red;"> Converting Data Type on Existing Arrays </h3>
The best way to change the data type of an existing array, is to make a copy of the array with the <b>astype()</b> method

In [65]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

print("The first data type is: ", arr.dtype)

newarr = arr.astype('i')

print("The array is :", newarr)
print("The changed data type is: ", newarr.dtype)

The first data type is:  float64
The array is : [1 2 3]
The changed data type is:  int32


In [68]:
import numpy as np

arr = np.array([1, 0, -3])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


<h3 style="color:red;"> NumPy Array Reshaping </h3>

* changing the shape of an array
* By reshaping we can add or remove dimensions or change number of elements in each dimension

<H4>Reshape From 1-D to 2-D</H4>

In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, -1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


<h4>Reshape From 1-D to 3-D </h4>

In [76]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, -1)  #you can pass -1 to one unknown dimension

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


<h4>Reshape From 2-D to 3-D </h4>

In [83]:
import numpy as np

# create a 2D array
a = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6],[1,2,3], [4,5,6],[1,2,3], [4,5,6]])

print(a.shape) 
# shape of a = (8,3)

b = a.reshape(2, 4, -1)
# changing the shape, -1 means any number which is suitable

print(b) 
# size of b = (8,3,1)

(8, 3)
[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


<h3 style="color:red;"> Flattening the arrays </h3>

* converting a multidimensional array into a 1D array
* we can use reshape(-1)

In [85]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


<h3 style="color:red;"> NumPy Array Iterating </h3>


In [87]:
#Iterating 1-D Arrays
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [88]:
#Iterating 2-D Arrays
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [89]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [ ]:
arr()

In [90]:
# Iterating 3-D Arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
      print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [95]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
#     print(y)
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


<h3 style="color:red;"> Joining NumPy Arrays </h3>

we join numpy array using <b>concatenate()</b> function

In [99]:
#join 1-D array
# Join two 2-D arrays 

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6, 7])

arr = np.concatenate((arr1, arr2, arr3))

print(arr)

[1 2 3 4 5 6 4 5 6 7]


In [104]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]
