<h1>Numpy</h1>


<h2 style="color:blue;">Introduction</h2> 

* NumPy is a Python library used for working with arrays​ 
    
 * NumPy was created in 2005 by Travis Oliphant.​ 
    
* It is open source​ 
    
* The array object in NumPy is called ndarray

* NumPy stands for Numerical Python

<h3 style="color:red;">Why use numpy?</h3>

* has array object which is 50x faster than Python list
  
* functions for working in domain of linear algebra, fourier transform, and matrices​
  
* the array object in NumPy is called ndarray

<h3 style="color:red;"> Why numpy is faster? </h3>

 * NumPy arrays are stored at one continuous place in memory unlike lists (locality of reference)
   
 * written in C or C++ for fast computation (python is partially used)

In [1]:
#install numpy
! pip install numpy

DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [1]:
! dir 

 Volume in drive C is New Volume
 Volume Serial Number is DA9E-831C

 Directory of C:\Users\us\Documents\python_tutorials

12/12/2023  08:06 AM    <DIR>          .
12/12/2023  08:06 AM    <DIR>          ..
12/12/2023  08:00 AM    <DIR>          .ipynb_checkpoints
12/09/2023  04:52 PM    <DIR>          basic_python
12/05/2023  09:51 AM            43,423 Day2_python_basics.ipynb
12/07/2023  07:32 AM            51,630 Day3_python_basics.ipynb
12/07/2023  10:13 AM            28,326 Day4_python_basics.ipynb
12/08/2023  08:17 AM            43,170 Day5_python_basics.ipynb
12/10/2023  08:10 AM            31,250 Day_1_python_basics.ipynb
12/07/2023  10:46 PM            13,086 exercise_python.docx
12/10/2023  08:19 AM    <DIR>          First_git
12/11/2023  10:08 AM            46,594 Github.pptx
12/08/2023  07:43 AM                70 new_file.txt
12/12/2023  08:06 AM            10,238 Numpy.ipynb
12/08/2023  07:22 AM               178 sample.txt.txt
12/12/2023  07:41 AM    <DIR>          Second 

In [5]:
pwd

'C:\\Users\\us\\Documents\\python_tutorials'

In [6]:
#check numpy version 

import numpy as np

print(np.__version__)

1.21.5


In [7]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
 # NumPy is usually imported under the np alias  
# In Python alias are an alternate name for referring to the same thing

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<h3 style="color:red;"> Dimensions in Arrays </h3>

<h3 style="color:red;"> 0-D Arrays </h3>


In [10]:
import numpy as np

arr = np.array(42)

print(arr)
# print(arr.ndim, 99999999)

print("The dimension of the above array is :", arr.ndim)

42
0 99999999
The dimension of the above array is : 0


<h3 style="color:red;"> 1-D Arrays </h3>

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


print("The dimension of the above array is :", arr.ndim)

[1 2 3 4 5]
The dimension of the above array is : 1


In [14]:
#access 1-D array

print(arr[-3])

3


In [79]:
#slicing 1-D array

arr[1:3]   #arr[-3:-1]

array([2, 3])

<h3 style="color:red;"> 2-D Arrays </h3>

In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 5, 7, 9], [4, 5, 6,1, 7, 8]])

print(arr)

print("The dimension of the above array is :", arr.ndim)

[[1 2 3 5 7 9]
 [4 5 6 1 7 8]]
The dimension of the above array is : 2


In [21]:
#access 2-D array
print(arr[0, 4])


7


In [85]:
#slicing of 2-D array
arr[1, 1:5]

array([5, 6, 1, 7])

<h3 style="color:red;"> 3-D arrays </h3>

In [23]:
import numpy as np

arr = np.array([[[1, 2, 3, 6, 8], [4, 5, 6, 77, 8]], [[1, 2, 3, 5, 7], [4, 5, 6, 2, 4]]])

print(arr)

print("The dimension of the above array is :", arr.ndim)


[[[ 1  2  3  6  8]
  [ 4  5  6 77  8]]

 [[ 1  2  3  5  7]
  [ 4  5  6  2  4]]]
The dimension of the above array is : 3


In [27]:
#access 3-D array
print(arr[0,1,4])

#negative indexing
# print(arr[1,1,-1])

8


In [102]:
#slicing 3-D array

print(arr[0, 0, 1:2])

[2]


In [29]:
#SPECIFY DIMENSION IN ARRAY
import numpy as np

arr = np.array([3, 6, 99], ndmin=3)
print(arr)

[[[ 3  6 99]]]
